name: GitHub Actions Demo
on: [pull_request]
env:
  GITHUB_PR_NUMBER: ${{github.event.pull_request.diff_url}}
  GITHUB_COMMIT_ID: ${{github.event.pull_request.head.sha}}
jobs:
  prJob:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "$GITHUB_PR_NUMBER and $GITHUB_COMMIT_ID"
